dateModified: 1592109362
email:
  fromEmail: JJimmyFlynn@gmail.com
  fromName: Sukiya
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  b21b0370-d516-4c56-a292-168d2756e594:
    name: Common
plugins:
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  imager-x:
    edition: pro
    enabled: true
    schemaVersion: 3.0.0
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
sections:
  46c553f5-16c5-4faa-93bb-a3228a66a676:
    enableVersioning: true
    entryTypes:
      a652db6e-5547-43d3-a1c4-e5a5879ab661:
        handle: homepage
        hasTitleField: false
        name: Homepage
        sortOrder: 1
        titleFormat: '{section.name|raw}'
        titleLabel: ''
    handle: homepage
    name: Homepage
    propagationMethod: all
    siteSettings:
      b715e7de-0810-4436-8ac2-7dd69090841c:
        enabledByDefault: true
        hasUrls: true
        template: index
        uriFormat: homepage
    type: single
  db60e867-bdfe-4cd2-b766-ba2ba93db522:
    enableVersioning: true
    entryTypes:
      75f9bd9f-feb0-4e78-80f6-1992e5674a20:
        handle: errors
        hasTitleField: true
        name: Errors
        sortOrder: 1
        titleFormat: null
        titleLabel: Title
    handle: errors
    name: Errors
    propagationMethod: all
    siteSettings:
      b715e7de-0810-4436-8ac2-7dd69090841c:
        enabledByDefault: true
        hasUrls: false
        template: null
        uriFormat: ''
    structure:
      maxLevels: 1
      uid: b3df0e0d-de17-4b01-8bd1-b90fc8b78e22
    type: structure
siteGroups:
  5345b501-22d8-4834-bcec-e0c884660ae4:
    name: Sukiya
sites:
  b715e7de-0810-4436-8ac2-7dd69090841c:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: Sukiya
    primary: true
    siteGroup: 5345b501-22d8-4834-bcec-e0c884660ae4
    sortOrder: 1
system:
  edition: solo
  live: true
  name: Sukiya
  schemaVersion: 3.4.10
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
volumes:
  7cfad959-f20e-444f-98e9-e9765eff2bb8:
    handle: media
    hasUrls: false
    name: Media
    settings:
      path: '@webroot/media'
    sortOrder: 1
    type: craft\volumes\Local
    url: ''
